import Foundation

/// Finds embedded kit targets generated by `score package swiftui` and
/// regenerates them in place.
///
/// `score dev` and `score build` call this before every compile, so an
/// embedded kit can never drift from the application's records and routes:
/// changing a `Record` or a `RouteCollection` updates the kit on the next
/// build, and consuming SwiftUI apps pick the change up on their next
/// dependency update.
public enum KitRegenerator {

    /// Regenerate every embedded kit found under `sourcesDirectory`.
    ///
    /// A directory is treated as a kit when it contains a `ScoreRecord.swift`
    /// starting with the generated-code marker. Returns the names of the kits
    /// that were regenerated.
    @discardableResult
    public static func regenerateEmbeddedKits(sourcesDirectory: String = "Sources") -> [String] {
        let fm = FileManager.default
        guard let entries = try? fm.contentsOfDirectory(atPath: sourcesDirectory) else { return [] }

        var regenerated: [String] = []
        for entry in entries.sorted() {
            let shimPath = "\(sourcesDirectory)/\(entry)/ScoreRecord.swift"
            guard let shim = try? String(contentsOfFile: shimPath, encoding: .utf8),
                shim.contains(SwiftUIKitExporter.generatedMarker)
            else { continue }

            let exporter = SwiftUIKitExporter(
                options: .init(
                    kitName: entry,
                    sourcesDirectory: sourcesDirectory,
                    excludedDirectories: [entry]
                ))
            let target = URL(fileURLWithPath: "\(sourcesDirectory)/\(entry)")
            if let result = try? exporter.exportTarget(into: target),
                !result.filesChanged.isEmpty
            {
                regenerated.append(entry)
            }
        }
        return regenerated
    }
}
